/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomerOrder {
  'id' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'totalAmount' : number,
  'address' : string,
  'timestamp' : Time,
  'items' : Array<OrderItem>,
  'phoneNumber' : string,
}
export interface OrderItem { 'productName' : string, 'quantity' : number }
export type OrderStatus = { 'pending' : null } |
  { 'confirmed' : null };
export interface Product { 'name' : string, 'pricePerKg' : number }
export type Time = bigint;
export interface _SERVICE {
  'getAllOrders' : ActorMethod<[], Array<CustomerOrder>>,
  'getAllOrdersByCustomerName' : ActorMethod<[], Array<CustomerOrder>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getOrder' : ActorMethod<[bigint], CustomerOrder>,
  'getProduct' : ActorMethod<[string], Product>,
  'getShopName' : ActorMethod<[], string>,
  'placeOrder' : ActorMethod<
    [string, string, string, Array<OrderItem>],
    bigint
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];