/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const OrderItem = IDL.Record({
  'productName' : IDL.Text,
  'quantity' : IDL.Float64,
});
export const CustomerOrder = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'totalAmount' : IDL.Float64,
  'address' : IDL.Text,
  'timestamp' : Time,
  'items' : IDL.Vec(OrderItem),
  'phoneNumber' : IDL.Text,
});
export const Product = IDL.Record({
  'name' : IDL.Text,
  'pricePerKg' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getAllOrders' : IDL.Func([], [IDL.Vec(CustomerOrder)], ['query']),
  'getAllOrdersByCustomerName' : IDL.Func(
      [],
      [IDL.Vec(CustomerOrder)],
      ['query'],
    ),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [CustomerOrder], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getShopName' : IDL.Func([], [IDL.Text], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(OrderItem)],
      [IDL.Nat],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const OrderItem = IDL.Record({
    'productName' : IDL.Text,
    'quantity' : IDL.Float64,
  });
  const CustomerOrder = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'totalAmount' : IDL.Float64,
    'address' : IDL.Text,
    'timestamp' : Time,
    'items' : IDL.Vec(OrderItem),
    'phoneNumber' : IDL.Text,
  });
  const Product = IDL.Record({ 'name' : IDL.Text, 'pricePerKg' : IDL.Float64 });
  
  return IDL.Service({
    'getAllOrders' : IDL.Func([], [IDL.Vec(CustomerOrder)], ['query']),
    'getAllOrdersByCustomerName' : IDL.Func(
        [],
        [IDL.Vec(CustomerOrder)],
        ['query'],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [CustomerOrder], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getShopName' : IDL.Func([], [IDL.Text], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(OrderItem)],
        [IDL.Nat],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };